part of 'pages.dart';

class DataPenelitianPreJigsaw extends StatelessWidget {
  const DataPenelitianPreJigsaw({super.key});

  @override
  Widget build(BuildContext context) {
    return GeneralPage(
      title: 'Data Penelitian',
      subtitle: 'Pre-test Kooperatif Tipe Jigsaw',
      child: SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Container(
                margin: EdgeInsets.fromLTRB(10, 10, 10, 0),
                child: Text(
                  "Scroll ke samping untuk melihat semua data",
                  style: blackFontStyle.copyWith(
                    fontSize: 16,
                  ),
                ),
              ),
              Container(
                margin: EdgeInsets.fromLTRB(10, 10, 10, 0),
                child: DataTable(
                  border: TableBorder.all(
                    width: 3.0,
                    color: "FAFAFC".toColor(),
                  ),
                  columns: [
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                  ],
                  rows: [
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('2')),
                        DataCell(Text('24,35')),
                        DataCell(Text('11')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('52,04')),
                        DataCell(Text('38,90')),
                        DataCell(Text('62,06')),
                        DataCell(Text('38,58')),
                        DataCell(Text('47,90')),
                        DataCell(Text('50,59')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('2')),
                        DataCell(Text('52,04')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('52,04')),
                        DataCell(Text('38,90')),
                        DataCell(Text('50,88')),
                        DataCell(Text('47,14')),
                        DataCell(Text('47,24')),
                        DataCell(Text('56,355')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('23,47')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('52,04')),
                        DataCell(Text('53,70')),
                        DataCell(Text('51,81')),
                        DataCell(Text('47,14')),
                        DataCell(Text('51,17')),
                        DataCell(Text('52,5575')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('2')),
                        DataCell(Text('3')),
                        DataCell(Text('23,5')),
                        DataCell(Text('17')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('35,71')),
                        DataCell(Text('53,70')),
                        DataCell(Text('52,16')),
                        DataCell(Text('64,28')),
                        DataCell(Text('51,46')),
                        DataCell(Text('51,615')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('2')),
                        DataCell(Text('24,35')),
                        DataCell(Text('11')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('52,04')),
                        DataCell(Text('38,90')),
                        DataCell(Text('62,06')),
                        DataCell(Text('38,58')),
                        DataCell(Text('47,90')),
                        DataCell(Text('50,59')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('24,47')),
                        DataCell(Text('11')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('52,04')),
                        DataCell(Text('53,70')),
                        DataCell(Text('63,46')),
                        DataCell(Text('38,58')),
                        DataCell(Text('51,95')),
                        DataCell(Text('46,995')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('2')),
                        DataCell(Text('24,85')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('52,04')),
                        DataCell(Text('38,90')),
                        DataCell(Text('67,89')),
                        DataCell(Text('55,71')),
                        DataCell(Text('53,64')),
                        DataCell(Text('63,5225')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('23,17')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('52,04')),
                        DataCell(Text('53,70')),
                        DataCell(Text('48,32')),
                        DataCell(Text('47,14')),
                        DataCell(Text('50,30')),
                        DataCell(Text('45,1825')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('4')),
                        DataCell(Text('3')),
                        DataCell(Text('23,37')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('68,37')),
                        DataCell(Text('53,70')),
                        DataCell(Text('50,65')),
                        DataCell(Text('55,71')),
                        DataCell(Text('57,11')),
                        DataCell(Text('50,7375')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('4')),
                        DataCell(Text('2')),
                        DataCell(Text('24,06')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('68,37')),
                        DataCell(Text('38,90')),
                        DataCell(Text('58,69')),
                        DataCell(Text('55,71')),
                        DataCell(Text('55,42')),
                        DataCell(Text('52,455')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('2')),
                        DataCell(Text('3')),
                        DataCell(Text('25,1')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('35,71')),
                        DataCell(Text('53,70')),
                        DataCell(Text('70,80')),
                        DataCell(Text('55,71')),
                        DataCell(Text('53,98')),
                        DataCell(Text('49,7725')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('2')),
                        DataCell(Text('23,48')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('52,04')),
                        DataCell(Text('38,90')),
                        DataCell(Text('51,93')),
                        DataCell(Text('47,14')),
                        DataCell(Text('47,50')),
                        DataCell(Text('57,56')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('2')),
                        DataCell(Text('22,37')),
                        DataCell(Text('19')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('52,04')),
                        DataCell(Text('38,90')),
                        DataCell(Text('38,99')),
                        DataCell(Text('72,85')),
                        DataCell(Text('50,70')),
                        DataCell(Text('49,5025')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('22,81')),
                        DataCell(Text('17')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('52,04')),
                        DataCell(Text('38,90')),
                        DataCell(Text('62,06')),
                        DataCell(Text('38,58')),
                        DataCell(Text('47,90')),
                        DataCell(Text('50,59')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('2')),
                        DataCell(Text('24,35')),
                        DataCell(Text('11')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('52,04')),
                        DataCell(Text('53,70')),
                        DataCell(Text('44,12')),
                        DataCell(Text('64,28')),
                        DataCell(Text('53,54')),
                        DataCell(Text('48,0775')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('2')),
                        DataCell(Text('22,7')),
                        DataCell(Text('17')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('35,71')),
                        DataCell(Text('53,70')),
                        DataCell(Text('42,84')),
                        DataCell(Text('64,28')),
                        DataCell(Text('49,13')),
                        DataCell(Text('53,2275')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('2')),
                        DataCell(Text('4')),
                        DataCell(Text('22,7')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('35,71')),
                        DataCell(Text('68,50')),
                        DataCell(Text('42,84')),
                        DataCell(Text('47,14')),
                        DataCell(Text('48,55')),
                        DataCell(Text('49,0775')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('2')),
                        DataCell(Text('4')),
                        DataCell(Text('24,13')),
                        DataCell(Text('11')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('35,71')),
                        DataCell(Text('68,50')),
                        DataCell(Text('59,50')),
                        DataCell(Text('38,58')),
                        DataCell(Text('50,57')),
                        DataCell(Text('55,215')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('4')),
                        DataCell(Text('22,07')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('52,04')),
                        DataCell(Text('68,50')),
                        DataCell(Text('35,50')),
                        DataCell(Text('55,71')),
                        DataCell(Text('52,94')),
                        DataCell(Text('46,215')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('22,59')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('52,04')),
                        DataCell(Text('53,70')),
                        DataCell(Text('41,56')),
                        DataCell(Text('47,14')),
                        DataCell(Text('48,61')),
                        DataCell(Text('43,4925')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('2')),
                        DataCell(Text('3')),
                        DataCell(Text('22,7')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('35,71')),
                        DataCell(Text('53,70')),
                        DataCell(Text('42,84')),
                        DataCell(Text('55,71')),
                        DataCell(Text('46,99')),
                        DataCell(Text('54,0525')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('4')),
                        DataCell(Text('2')),
                        DataCell(Text('22,48')),
                        DataCell(Text('11')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('68,37')),
                        DataCell(Text('38,90')),
                        DataCell(Text('40,28')),
                        DataCell(Text('38,58')),
                        DataCell(Text('46,53')),
                        DataCell(Text('43,9075')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('2')),
                        DataCell(Text('22,59')),
                        DataCell(Text('11')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('52,04')),
                        DataCell(Text('38,90')),
                        DataCell(Text('41,56')),
                        DataCell(Text('38,58')),
                        DataCell(Text('42,77')),
                        DataCell(Text('42,255')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('22,14')),
                        DataCell(Text('11')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('52,04')),
                        DataCell(Text('53,70')),
                        DataCell(Text('36,31')),
                        DataCell(Text('38,58')),
                        DataCell(Text('45,16')),
                        DataCell(Text('42,18')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('2')),
                        DataCell(Text('24,08')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('52,04')),
                        DataCell(Text('38,90')),
                        DataCell(Text('58,92')),
                        DataCell(Text('47,14')),
                        DataCell(Text('49,25')),
                        DataCell(Text('48,5675')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('22,98')),
                        DataCell(Text('11')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('52,04')),
                        DataCell(Text('53,70')),
                        DataCell(Text('46,10')),
                        DataCell(Text('38,58')),
                        DataCell(Text('47,61')),
                        DataCell(Text('46,8925')),
                      ],
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
