part of 'pages.dart';

class DataPenelitianPreStad extends StatelessWidget {
  const DataPenelitianPreStad({super.key});

  @override
  Widget build(BuildContext context) {
    return GeneralPage(
      title: 'Data Penelitian',
      subtitle: 'Pre-test Kooperatif Tipe STAD',
      child: SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Container(
                margin: EdgeInsets.fromLTRB(10, 10, 10, 0),
                child: Text(
                  "Scroll ke samping untuk melihat semua data",
                  style: blackFontStyle.copyWith(
                    fontSize: 16,
                  ),
                ),
              ),
              Container(
                margin: EdgeInsets.fromLTRB(10, 10, 10, 0),
                child: DataTable(
                  border: TableBorder.all(
                    width: 3.0,
                    color: "FAFAFC".toColor(),
                  ),
                  columns: [
                    DataColumn(
                      label: Text(
                        "Heading",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "Passing",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "Dribling",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "Shooting",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                  ],
                  rows: [
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('5')),
                        DataCell(Text('23,35')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('49,00')),
                        DataCell(Text('62,44')),
                        DataCell(Text('62,06')),
                        DataCell(Text('52,25')),
                        DataCell(Text('56,44')),
                        DataCell(Text('62,71')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('56,4375')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('5')),
                        DataCell(Text('2')),
                        DataCell(Text('22,39')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('73,10')),
                        DataCell(Text('36,10')),
                        DataCell(Text('50,88')),
                        DataCell(Text('52,25')),
                        DataCell(Text('53,08')),
                        DataCell(Text('52,31')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('53,0825')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('5')),
                        DataCell(Text('22,47')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('49,00')),
                        DataCell(Text('62,44')),
                        DataCell(Text('51,81')),
                        DataCell(Text('43,26')),
                        DataCell(Text('51,63')),
                        DataCell(Text('48,68')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('51,6275')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('2')),
                        DataCell(Text('3')),
                        DataCell(Text('22,47')),
                        DataCell(Text('17')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('36,94')),
                        DataCell(Text('44,88')),
                        DataCell(Text('52,16')),
                        DataCell(Text('61,23')),
                        DataCell(Text('48,80')),
                        DataCell(Text('55,62')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('48,8025')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('23,47')),
                        DataCell(Text('11')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('49,00')),
                        DataCell(Text('44,88')),
                        DataCell(Text('63,46')),
                        DataCell(Text('34,28')),
                        DataCell(Text('47,91')),
                        DataCell(Text('53,85')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('47,905')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('4')),
                        DataCell(Text('23,85')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('49,00')),
                        DataCell(Text('53,66')),
                        DataCell(Text('67,89')),
                        DataCell(Text('52,25')),
                        DataCell(Text('55,70')),
                        DataCell(Text('52,30')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('55,7')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('22,17')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('49,00')),
                        DataCell(Text('44,88')),
                        DataCell(Text('48,32')),
                        DataCell(Text('43,26')),
                        DataCell(Text('46,37')),
                        DataCell(Text('43,93')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('46,365')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('4')),
                        DataCell(Text('3')),
                        DataCell(Text('22,37')),
                        DataCell(Text('17')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('61,05')),
                        DataCell(Text('44,88')),
                        DataCell(Text('50,65')),
                        DataCell(Text('61,23')),
                        DataCell(Text('54,45')),
                        DataCell(Text('58,44')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('54,4525')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('4')),
                        DataCell(Text('4')),
                        DataCell(Text('23,06')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('61,05')),
                        DataCell(Text('53,66')),
                        DataCell(Text('58,69')),
                        DataCell(Text('52,25')),
                        DataCell(Text('56,41')),
                        DataCell(Text('55,31')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('56,4125')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('5')),
                        DataCell(Text('3')),
                        DataCell(Text('24,1')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('73,10')),
                        DataCell(Text('44,88')),
                        DataCell(Text('70,80')),
                        DataCell(Text('52,25')),
                        DataCell(Text('60,26')),
                        DataCell(Text('45,79')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('60,2575')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('5')),
                        DataCell(Text('22,48')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('49,00')),
                        DataCell(Text('62,44')),
                        DataCell(Text('51,93')),
                        DataCell(Text('43,26')),
                        DataCell(Text('51,66')),
                        DataCell(Text('43,46')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('51,6575')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('2')),
                        DataCell(Text('21,37')),
                        DataCell(Text('19')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('49,00')),
                        DataCell(Text('36,10')),
                        DataCell(Text('38,99')),
                        DataCell(Text('70,21')),
                        DataCell(Text('48,58')),
                        DataCell(Text('49,14')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('48,575')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('2')),
                        DataCell(Text('21,37')),
                        DataCell(Text('19')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('49,00')),
                        DataCell(Text('36,10')),
                        DataCell(Text('38,99')),
                        DataCell(Text('70,21')),
                        DataCell(Text('48,58')),
                        DataCell(Text('49,14')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('48,575')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('6')),
                        DataCell(Text('21,81')),
                        DataCell(Text('19')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('49,00')),
                        DataCell(Text('71,22')),
                        DataCell(Text('44,12')),
                        DataCell(Text('70,21')),
                        DataCell(Text('58,64')),
                        DataCell(Text('52,54')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('58,6375')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('2')),
                        DataCell(Text('3')),
                        DataCell(Text('21,7')),
                        DataCell(Text('17')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('36,94')),
                        DataCell(Text('44,88')),
                        DataCell(Text('42,84')),
                        DataCell(Text('61,23')),
                        DataCell(Text('46,47')),
                        DataCell(Text('42,08')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('46,4725')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('2')),
                        DataCell(Text('4')),
                        DataCell(Text('21,7')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('36,94')),
                        DataCell(Text('53,66')),
                        DataCell(Text('42,84')),
                        DataCell(Text('52,25')),
                        DataCell(Text('46,42')),
                        DataCell(Text('60,28')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('46,4225')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('2')),
                        DataCell(Text('4')),
                        DataCell(Text('23,13')),
                        DataCell(Text('11')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('36,94')),
                        DataCell(Text('53,66')),
                        DataCell(Text('59,50')),
                        DataCell(Text('34,28')),
                        DataCell(Text('46,10')),
                        DataCell(Text('41,10')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('46,095')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('4')),
                        DataCell(Text('21,07')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('49,00')),
                        DataCell(Text('53,66')),
                        DataCell(Text('35,50')),
                        DataCell(Text('52,25')),
                        DataCell(Text('47,60')),
                        DataCell(Text('45,55')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('47,6025')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('5')),
                        DataCell(Text('21,59')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('49,00')),
                        DataCell(Text('62,44')),
                        DataCell(Text('41,56')),
                        DataCell(Text('52,25')),
                        DataCell(Text('51,31')),
                        DataCell(Text('51,04')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('51,3125')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('2')),
                        DataCell(Text('3')),
                        DataCell(Text('21,7')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('36,94')),
                        DataCell(Text('44,88')),
                        DataCell(Text('42,84')),
                        DataCell(Text('52,25')),
                        DataCell(Text('44,23')),
                        DataCell(Text('46,11')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('44,2275')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('4')),
                        DataCell(Text('2')),
                        DataCell(Text('21,48')),
                        DataCell(Text('11')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('61,05')),
                        DataCell(Text('36,10')),
                        DataCell(Text('40,28')),
                        DataCell(Text('34,28')),
                        DataCell(Text('42,93')),
                        DataCell(Text('50,02')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('42,9275')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('5')),
                        DataCell(Text('21,59')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('49,00')),
                        DataCell(Text('62,44')),
                        DataCell(Text('41,56')),
                        DataCell(Text('43,26')),
                        DataCell(Text('49,07')),
                        DataCell(Text('42,85')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('49,065')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('21,14')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('49,00')),
                        DataCell(Text('44,88')),
                        DataCell(Text('36,31')),
                        DataCell(Text('43,26')),
                        DataCell(Text('43,36')),
                        DataCell(Text('44,64')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('43,3625')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('2')),
                        DataCell(Text('23,08')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('49,00')),
                        DataCell(Text('36,10')),
                        DataCell(Text('58,92')),
                        DataCell(Text('43,26')),
                        DataCell(Text('46,82')),
                        DataCell(Text('51,15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('46,82')),
                        DataCell(Text('1')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('21,98')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('49,00')),
                        DataCell(Text('44,88')),
                        DataCell(Text('46,10')),
                        DataCell(Text('43,26')),
                        DataCell(Text('45,81')),
                        DataCell(Text('51,10')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('45,81')),
                        DataCell(Text('1')),
                      ],
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
