part of 'pages.dart';

class DataPenelitianPage extends StatelessWidget {
  const DataPenelitianPage({super.key});

  @override
  Widget build(BuildContext context) {
    return GeneralPage(
      title: 'Data Penelitian',
      subtitle: 'Pre-test Kooperatif Tipe TGT',
      child: SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Container(
                margin: EdgeInsets.fromLTRB(10, 10, 10, 0),
                child: Text(
                  "Scroll ke samping untuk melihat semua data",
                  style: blackFontStyle.copyWith(
                    fontSize: 16,
                  ),
                ),
              ),
              Container(
                margin: EdgeInsets.fromLTRB(10, 10, 10, 0),
                child: DataTable(
                  border: TableBorder.all(
                    width: 3.0,
                    color: "FAFAFC".toColor(),
                  ),
                  columns: [
                    DataColumn(
                      label: Text(
                        "Heading",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "Passing",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "Dribling",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "Shooting",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "Pre",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "Pre",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "Pre",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "Pre",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "Pre",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                    DataColumn(
                      label: Text(
                        "",
                        style: blackFontStyle.copyWith(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
                    ),
                  ],
                  rows: [
                    DataRow(
                      cells: [
                        DataCell(Text('4')),
                        DataCell(Text('3')),
                        DataCell(Text('23,3')),
                        DataCell(Text('16')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('1')),
                        DataCell(Text('3')),
                        DataCell(Text('4')),
                        DataCell(Text('5')),
                        DataCell(Text('6')),
                        DataCell(Text('16')),
                        DataCell(Text('')),
                        DataCell(Text('56,2')),
                        DataCell(Text('52,04')),
                        DataCell(Text('62,06')),
                        DataCell(Text('52,46')),
                        DataCell(Text('230,58')),
                        DataCell(Text('233,49')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('2')),
                        DataCell(Text('22,34')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('5')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('1')),
                        DataCell(Text('3')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('48,73')),
                        DataCell(Text('35,71')),
                        DataCell(Text('50,88')),
                        DataCell(Text('47,92')),
                        DataCell(Text('183,24')),
                        DataCell(Text('177,80')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('22,42')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('5')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('1')),
                        DataCell(Text('3')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('48,73')),
                        DataCell(Text('52,04')),
                        DataCell(Text('51,81')),
                        DataCell(Text('47,92')),
                        DataCell(Text('200,50')),
                        DataCell(Text('204,23')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('2')),
                        DataCell(Text('3')),
                        DataCell(Text('22,45')),
                        DataCell(Text('19')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('5')),
                        DataCell(Text('5')),
                        DataCell(Text('5')),
                        DataCell(Text('1')),
                        DataCell(Text('3')),
                        DataCell(Text('19')),
                        DataCell(Text('')),
                        DataCell(Text('33,43')),
                        DataCell(Text('52,04')),
                        DataCell(Text('52,16')),
                        DataCell(Text('66,05')),
                        DataCell(Text('203,68')),
                        DataCell(Text('190,92')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('23,42')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('5')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('1')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('64,02')),
                        DataCell(Text('35,71')),
                        DataCell(Text('67,89')),
                        DataCell(Text('47,92')),
                        DataCell(Text('215,54')),
                        DataCell(Text('201,90')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('4')),
                        DataCell(Text('2')),
                        DataCell(Text('23,8')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('5')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('1')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('48,73')),
                        DataCell(Text('52,04')),
                        DataCell(Text('63,46')),
                        DataCell(Text('47,92')),
                        DataCell(Text('212,15')),
                        DataCell(Text('237,93')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('22,12')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('1')),
                        DataCell(Text('2')),
                        DataCell(Text('2')),
                        DataCell(Text('5')),
                        DataCell(Text('1')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('48,73')),
                        DataCell(Text('52,04')),
                        DataCell(Text('48,32')),
                        DataCell(Text('38,86')),
                        DataCell(Text('187,95')),
                        DataCell(Text('207,19')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('4')),
                        DataCell(Text('3')),
                        DataCell(Text('22,32')),
                        DataCell(Text('17')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('1')),
                        DataCell(Text('3')),
                        DataCell(Text('5')),
                        DataCell(Text('3')),
                        DataCell(Text('5')),
                        DataCell(Text('17')),
                        DataCell(Text('')),
                        DataCell(Text('64,02')),
                        DataCell(Text('52,04')),
                        DataCell(Text('50,65')),
                        DataCell(Text('56,99')),
                        DataCell(Text('223,70')),
                        DataCell(Text('206,84')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('4')),
                        DataCell(Text('3')),
                        DataCell(Text('23,01')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('1')),
                        DataCell(Text('5')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('64,02')),
                        DataCell(Text('52,04')),
                        DataCell(Text('58,69')),
                        DataCell(Text('47,92')),
                        DataCell(Text('222,67')),
                        DataCell(Text('224,96')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('4')),
                        DataCell(Text('3')),
                        DataCell(Text('24,05')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('1')),
                        DataCell(Text('5')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('48,73')),
                        DataCell(Text('52,04')),
                        DataCell(Text('70,8')),
                        DataCell(Text('47,92')),
                        DataCell(Text('219,49')),
                        DataCell(Text('192,73')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('2')),
                        DataCell(Text('22,43')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('1')),
                        DataCell(Text('7')),
                        DataCell(Text('3')),
                        DataCell(Text('1')),
                        DataCell(Text('1')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('48,73')),
                        DataCell(Text('35,71')),
                        DataCell(Text('51,93')),
                        DataCell(Text('38,86')),
                        DataCell(Text('175,23')),
                        DataCell(Text('217,61')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('2')),
                        DataCell(Text('21,32')),
                        DataCell(Text('21')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('5')),
                        DataCell(Text('3')),
                        DataCell(Text('5')),
                        DataCell(Text('3')),
                        DataCell(Text('5')),
                        DataCell(Text('21')),
                        DataCell(Text('')),
                        DataCell(Text('48,73')),
                        DataCell(Text('35,71')),
                        DataCell(Text('38,99')),
                        DataCell(Text('75,12')),
                        DataCell(Text('198,55')),
                        DataCell(Text('188,21')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('21,76')),
                        DataCell(Text('19')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('5')),
                        DataCell(Text('3')),
                        DataCell(Text('5')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('19')),
                        DataCell(Text('')),
                        DataCell(Text('48,73')),
                        DataCell(Text('52,04')),
                        DataCell(Text('44,12')),
                        DataCell(Text('66,05')),
                        DataCell(Text('210,94')),
                        DataCell(Text('206,46')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('21,65')),
                        DataCell(Text('17')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('5')),
                        DataCell(Text('3')),
                        DataCell(Text('5')),
                        DataCell(Text('1')),
                        DataCell(Text('3')),
                        DataCell(Text('17')),
                        DataCell(Text('')),
                        DataCell(Text('48,73')),
                        DataCell(Text('52,04')),
                        DataCell(Text('42,84')),
                        DataCell(Text('56,99')),
                        DataCell(Text('200,60')),
                        DataCell(Text('195,31')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('2')),
                        DataCell(Text('4')),
                        DataCell(Text('21,65')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('5')),
                        DataCell(Text('5')),
                        DataCell(Text('1')),
                        DataCell(Text('1')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('33,43')),
                        DataCell(Text('68,37')),
                        DataCell(Text('42,84')),
                        DataCell(Text('47,92')),
                        DataCell(Text('192,56')),
                        DataCell(Text('179,54')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('2')),
                        DataCell(Text('4')),
                        DataCell(Text('23,08')),
                        DataCell(Text('11')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('1')),
                        DataCell(Text('1')),
                        DataCell(Text('11')),
                        DataCell(Text('')),
                        DataCell(Text('33,43')),
                        DataCell(Text('68,37')),
                        DataCell(Text('59,5')),
                        DataCell(Text('29,79')),
                        DataCell(Text('191,09')),
                        DataCell(Text('227,16')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('4')),
                        DataCell(Text('21,02')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('48,73')),
                        DataCell(Text('68,37')),
                        DataCell(Text('35,5')),
                        DataCell(Text('47,92')),
                        DataCell(Text('200,52')),
                        DataCell(Text('165,30')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('21,54')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('1')),
                        DataCell(Text('5')),
                        DataCell(Text('3')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('48,73')),
                        DataCell(Text('52,04')),
                        DataCell(Text('41,56')),
                        DataCell(Text('47,92')),
                        DataCell(Text('190,25')),
                        DataCell(Text('193,32')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('2')),
                        DataCell(Text('3')),
                        DataCell(Text('21,65')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('1')),
                        DataCell(Text('3')),
                        DataCell(Text('1')),
                        DataCell(Text('5')),
                        DataCell(Text('5')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('33,43')),
                        DataCell(Text('52,04')),
                        DataCell(Text('42,84')),
                        DataCell(Text('47,92')),
                        DataCell(Text('176,23')),
                        DataCell(Text('191,21')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('4')),
                        DataCell(Text('2')),
                        DataCell(Text('21,43')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('5')),
                        DataCell(Text('1')),
                        DataCell(Text('15')),
                        DataCell(Text('')),
                        DataCell(Text('64,02')),
                        DataCell(Text('35,71')),
                        DataCell(Text('40,28')),
                        DataCell(Text('47,92')),
                        DataCell(Text('187,93')),
                        DataCell(Text('183,67')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('21,54')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('1')),
                        DataCell(Text('3')),
                        DataCell(Text('5')),
                        DataCell(Text('3')),
                        DataCell(Text('1')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('48,73')),
                        DataCell(Text('52,04')),
                        DataCell(Text('41,56')),
                        DataCell(Text('38,86')),
                        DataCell(Text('181,19')),
                        DataCell(Text('193,55')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('21,09')),
                        DataCell(Text('17')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('5')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('17')),
                        DataCell(Text('')),
                        DataCell(Text('48,73')),
                        DataCell(Text('52,04')),
                        DataCell(Text('36,31')),
                        DataCell(Text('56,99')),
                        DataCell(Text('194,07')),
                        DataCell(Text('188,21')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('3')),
                        DataCell(Text('2')),
                        DataCell(Text('23,03')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('1')),
                        DataCell(Text('1')),
                        DataCell(Text('3')),
                        DataCell(Text('13')),
                        DataCell(Text('')),
                        DataCell(Text('48,73')),
                        DataCell(Text('35,71')),
                        DataCell(Text('58,92')),
                        DataCell(Text('38,86')),
                        DataCell(Text('182,22')),
                        DataCell(Text('204,27')),
                      ],
                    ),
                    DataRow(
                      cells: [
                        DataCell(Text('4')),
                        DataCell(Text('3')),
                        DataCell(Text('21,93')),
                        DataCell(Text('17')),
                        DataCell(Text('')),
                        DataCell(Text('')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('5')),
                        DataCell(Text('3')),
                        DataCell(Text('3')),
                        DataCell(Text('17')),
                        DataCell(Text('')),
                        DataCell(Text('64,02')),
                        DataCell(Text('52,04')),
                        DataCell(Text('46,1')),
                        DataCell(Text('56,99')),
                        DataCell(Text('219,15')),
                        DataCell(Text('198,18')),
                      ],
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
